### ISSUE TITLE
Broken URL in README.md

### ISSUE THREAD

**Issue by SchrodingersGat** [dronecan/gui_tool#1]
The documentation URL in README.md is currently borken - see images below

![image](https://user-images.githubusercontent.com/10080325/143219978-9cc33173-3d11-4fe9-9f38-847e6953b898.png)

![image](https://user-images.githubusercontent.com/10080325/143220082-5fb5461e-50a9-4b43-9282-10127dad278e.png)

**Comment by SchrodingersGat** [comment]
As a further note, navigating to https://dronecan.github.io/gui_tool/ results in the following:

![image](https://user-images.githubusercontent.com/10080325/143220276-9a736c3c-ea7c-4708-8712-55b6239a8fce.png)

**Comment by davidbuzz** [comment]
fixed
